/**
 * 기업분석 결과 뷰 - JSON 스키마(metadata, analysis_sections, key_summary) 적용, 카드 스타일
 */

import React from "react";
import type { CompanyAnalysisResult } from "../utils/companyAnalysisApi";

function BlockTitle({ children, isFirst }: { children: React.ReactNode; isFirst?: boolean }) {
  return (
    <div
      className={
        isFirst
          ? "pb-0"
          : "mt-[26px] pt-[26px] pb-0 border-t border-white/8"
      }
    >
      <span style={{ fontSize: 16, fontWeight: 700, lineHeight: 1.5 }} className="text-white">
        {children}
      </span>
    </div>
  );
}

export function CompanyAnalysisResultView({
  data,
  embedded = true,
  onDelete,
}: {
  data: CompanyAnalysisResult;
  embedded?: boolean;
  onDelete?: () => void;
}) {
  const meta = data.metadata;
  const containerClass = embedded
    ? "flex-1 min-h-0 flex flex-col overflow-hidden bg-white/5 border border-white/8 rounded-[10px] mt-0 mb-6 mx-0"
    : "bg-white/5 border border-white/8 rounded-[10px] mt-0 mb-6 mx-0";
  const contentClass = embedded
    ? "flex-1 min-h-0 overflow-y-auto overflow-x-hidden"
    : "overflow-x-hidden";

  return (
    <div className={containerClass}>
      <div className={contentClass}>
        <div className="px-[17px] pt-[20px] pb-[20px] border-b border-white/8">
          {meta.last_updated && (
            <div style={{ fontSize: 11, lineHeight: 1.5 }} className="text-white/90">
              기준일: {meta.last_updated}
            </div>
          )}
          <div style={{ fontSize: 18, fontWeight: 700, lineHeight: 1.5 }} className="text-white">
            {meta.company_name || "기업 분석"}
          </div>
          <div style={{ fontSize: 11, lineHeight: 1.5 }} className="text-white/40 mt-[6px] flex items-center justify-between gap-3">
            <span>
              {(meta.ticker || meta.market) && (
                <span>{[meta.ticker, meta.market].filter(Boolean).join(" · ")}</span>
              )}
              <span className={meta.ticker || meta.market ? " ml-2" : ""}>Generated by Gemini AI</span>
            </span>
            {onDelete && (
              <button
                type="button"
                onClick={onDelete}
                className="text-white/70 hover:text-red-400 transition-colors shrink-0"
                style={{ fontSize: 11 }}
              >
                삭제하기
              </button>
            )}
          </div>
        </div>

        <div className="px-5 pt-6 pb-6">
          {data.analysis_sections.map((section, i) => (
            <div key={i}>
              <BlockTitle isFirst={i === 0}>{section.title || `분석 ${i + 1}`}</BlockTitle>
              <div
                style={{ fontSize: 14, lineHeight: 1.6 }}
                className="text-white/90 mt-[14px] whitespace-pre-line"
              >
                {section.content || "(내용 없음)"}
              </div>
            </div>
          ))}

          <BlockTitle isFirst={data.analysis_sections.length === 0}>핵심 요약</BlockTitle>
          <div className="mt-[14px] space-y-[12px]">
            {data.key_summary.growth_driver && (
              <div>
                <div style={{ fontSize: 13, fontWeight: 600 }} className="text-white/70 mb-1">
                  성장 요소
                </div>
                <div style={{ fontSize: 14, lineHeight: 1.5 }} className="text-white/90">
                  {data.key_summary.growth_driver}
                </div>
              </div>
            )}
            {data.key_summary.risk_factor && (
              <div>
                <div style={{ fontSize: 13, fontWeight: 600 }} className="text-white/70 mb-1">
                  리스크
                </div>
                <div style={{ fontSize: 14, lineHeight: 1.5 }} className="text-white/90">
                  {data.key_summary.risk_factor}
                </div>
              </div>
            )}
            {data.key_summary.overall_opinion && (
              <div className="pt-[18px] border-t border-white/8">
                <div style={{ fontSize: 13, fontWeight: 600 }} className="text-white/70 mb-2">
                  총평
                </div>
                <div style={{ fontSize: 14, lineHeight: 1.5 }} className="text-white/90 whitespace-pre-line">
                  {data.key_summary.overall_opinion}
                </div>
              </div>
            )}
          </div>

          {(data.sectors?.length ?? 0) > 0 && (
            <div className="mt-[22px] pt-[18px] border-t border-white/6 flex flex-wrap gap-2">
              {[...(data.sectors ?? [])]
                .sort((a, b) => a.localeCompare(b, "ko"))
                .map((sector, i) => {
                  const colors = ["bg-emerald-500/20 text-emerald-300", "bg-blue-500/20 text-blue-300", "bg-amber-500/20 text-amber-300", "bg-purple-500/20 text-purple-300", "bg-cyan-500/20 text-cyan-300"];
                  const colorClass = colors[i % colors.length];
                  return (
                    <span
                      key={i}
                      className={`inline-flex items-center rounded-full px-2.5 py-1 text-xs font-medium ${colorClass}`}
                    >
                      {sector}
                      <span className="ml-1 opacity-80">(1)</span>
                    </span>
                  );
                })}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
