/**
 * 인사이트 칩 리포트 뷰 - 기존 리포트 카드 UI 스타일 계승, 3단계 구조
 */

import React from "react";
import type { InsightReportData } from "../data/insightReport";

const lineStyle = { lineHeight: 1.5 as const };

function formatArticleDate(publishedAt?: string, options?: { withLabel?: boolean; dateOnly?: boolean }): string {
  if (!publishedAt) return "";
  try {
    const d = new Date(publishedAt);
    if (isNaN(d.getTime())) return options?.withLabel ? `발행: ${publishedAt}` : publishedAt;
    const formatted = options?.dateOnly
      ? `${d.getFullYear()}.${String(d.getMonth() + 1).padStart(2, "0")}.${String(d.getDate()).padStart(2, "0")}`
      : d.toLocaleString("ko-KR", {
          year: "numeric",
          month: "2-digit",
          day: "2-digit",
          hour: "2-digit",
          minute: "2-digit",
        });
    return options?.withLabel ? `발행: ${formatted}` : formatted;
  } catch {
    return options?.withLabel ? `발행: ${publishedAt}` : publishedAt;
  }
}

function BlockTitle({ children }: { children: React.ReactNode }) {
  return (
    <div className="mt-[26px] pt-[26px] pb-0 first:mt-0 first:pt-0 first:pb-0 border-t border-white/8 first:border-t-0">
      <span style={{ fontSize: 16, fontWeight: 700, lineHeight: 1.5 }} className="text-white">
        {children}
      </span>
    </div>
  );
}

const SCORE_LEGEND = [
  { range: "1 ~ 3점", label: "단기 소음 (Noise)", desc: "일상적인 변동성으로, 즉각적인 대응이 필요 없는 수준." },
  { range: "4 ~ 6점", label: "주의 (Watch)", desc: "시장 흐름에 영향을 줄 수 있어 지속적인 모니터링이 필요한 수준." },
  { range: "7 ~ 8점", label: "중요 (Significant)", desc: "자산 가치에 직접적인 영향을 미치며, 매수/매도 등의 구체적 행동이 권고되는 수준." },
  { range: "9 ~ 10점", label: "결정적 (Critical)", desc: "시장의 판도를 바꾸거나 종목의 본질적 가치를 훼손하는 핵심 변수 발생." },
];

export function InsightReportView({
  data,
  title,
  publishedAt,
  createdAt,
  aiModel,
  onDelete,
  embedded = true,
}: {
  data: InsightReportData;
  title?: string;
  source?: string;
  publishedAt?: string;
  createdAt?: string;
  dateStr?: string;
  aiModel?: "gemini" | "gpt" | "claude";
  onDelete?: () => void;
  /** false: 콘텐츠 높이대로 흐름, 부모가 스크롤 (SNS 피드 스타일) */
  embedded?: boolean;
}) {
  const bulletSize = 3;
  const bulletStyle = {
    width: bulletSize,
    height: bulletSize,
    borderRadius: "50%",
    flexShrink: 0,
    marginTop: 10,
  } as const;

  const signalColor =
    data.signal === "좋음" ? "text-emerald-400" : data.signal === "나쁨" ? "text-red-400" : "text-white/70";

  const scoreColor =
    data.score >= 9 ? "text-red-400" :
    data.score >= 7 ? "text-amber-400" :
    data.score >= 4 ? "text-yellow-500/90" :
    "text-white/50";

  const strategyText = data.strategy || "(전략 없음)";

  const dateDisplay = publishedAt
    ? formatArticleDate(publishedAt, { withLabel: true })
    : createdAt
      ? formatArticleDate(createdAt, { withLabel: true })
      : "";

  const containerClass = embedded
    ? "flex-1 min-h-0 flex flex-col overflow-hidden bg-white/5 border border-white/8 rounded-[10px] mt-0 mb-6 mx-0"
    : "bg-white/5 border border-white/8 rounded-[10px] mt-0 mb-6 mx-0";
  const contentClass = embedded
    ? "flex-1 min-h-0 overflow-y-auto overflow-x-hidden"
    : "overflow-x-hidden";

  return (
    <div className={containerClass}>
      <div className={contentClass}>
        <div className="px-[17px] pt-[20px] pb-[20px] border-b border-white/8">
          {dateDisplay && (
            <div style={{ fontSize: 11, lineHeight: 1.5 }} className="text-white/90">
              {dateDisplay}
            </div>
          )}
          <div style={{ fontSize: 18, fontWeight: 700, lineHeight: 1.5 }} className="text-white">
            {title ?? "인사이트 리포트"}
          </div>
          {(aiModel || onDelete) && (
            <div style={{ fontSize: 11, lineHeight: 1.5 }} className="text-white/40 mt-[6px] flex items-center justify-between gap-3">
              {aiModel ? (
                <span>Generated by {aiModel === "gemini" ? "Gemini AI" : aiModel === "claude" ? "Claude" : aiModel === "gpt" ? "ChatGPT" : "AI"}</span>
              ) : (
                <span />
              )}
              {onDelete && (
                <button
                  type="button"
                  onClick={onDelete}
                  className="text-white/70 hover:text-red-400 transition-colors shrink-0"
                  style={{ fontSize: 12 }}
                >
                  삭제하기
                </button>
              )}
            </div>
          )}
        </div>

        <div className="px-5 pt-6 pb-6">
          <BlockTitle>기사 요약</BlockTitle>
          <div className="mt-[14px] space-y-[10px]">
            {(data.articleSummary.length > 0 ? data.articleSummary : ["(요약 없음)"]).map((item, i) => (
              <div key={i} className="flex gap-2 items-start">
                <span style={bulletStyle} className="bg-white/50 block shrink-0" />
                <div style={{ fontSize: 14, lineHeight: 1.6, fontWeight: 500 }} className="text-white/90 whitespace-pre-line">
                  {item}
                </div>
              </div>
            ))}
          </div>

          <BlockTitle>핵심 포인트</BlockTitle>
          <div style={{ fontSize: 14, lineHeight: 1.6 }} className="text-white/80 mt-[14px]">
            {data.keyPoints || "(분석 없음)"}
          </div>

          <BlockTitle>투자 의견</BlockTitle>
          <div className="mt-[14px] space-y-[12px]">
            <div className="flex items-center gap-3 flex-wrap">
              <span style={{ fontSize: 14, fontWeight: 600 }} className="text-white/90">
                점수:
              </span>
              <span style={{ fontSize: 14 }} className={scoreColor}>
                {data.score}/10
              </span>
              <span style={{ fontSize: 14, fontWeight: 600 }} className="text-white/90">
                신호:
              </span>
              <span style={{ fontSize: 14 }} className={signalColor}>
                {data.signal}
              </span>
            </div>
            <div>
              <div style={{ fontSize: 13, fontWeight: 600 }} className="text-white/70 mb-2">
                전략
              </div>
              <div style={{ fontSize: 14, ...lineStyle }} className="text-white/90 whitespace-pre-line">
                {strategyText}
              </div>
            </div>

            <div className="mt-[22px] pt-[18px] border-t border-white/6 rounded-[8px] bg-white/5 border border-white/8 px-4 py-3">
              <div style={{ fontSize: 12, fontWeight: 600 }} className="text-white/70 mb-3">
                범례
              </div>
              <div className="space-y-3">
                {SCORE_LEGEND.map((item, i) => (
                  <div key={i} style={{ fontSize: 12, ...lineStyle }} className="text-white/60">
                    <span className="text-white/80 font-medium">{item.range} {item.label}</span>
                    <span className="block mt-0.5">{item.desc}</span>
                  </div>
                ))}
              </div>
            </div>

            {(data.labels?.length ?? 0) > 0 && (
              <div className="mt-[22px] pt-[18px] border-t border-white/6 flex flex-wrap gap-2">
                {data.labels!.map((label, i) => {
                  const colors = ["bg-emerald-500/20 text-emerald-300", "bg-blue-500/20 text-blue-300", "bg-amber-500/20 text-amber-300", "bg-purple-500/20 text-purple-300", "bg-cyan-500/20 text-cyan-300"];
                  const colorClass = colors[i % colors.length];
                  return (
                    <span
                      key={i}
                      className={`inline-flex items-center rounded-full px-3 py-1 text-sm font-medium ${colorClass}`}
                    >
                      {label}
                    </span>
                  );
                })}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
