import React, { useRef, useState, useEffect } from "react";
import { ShieldCheck } from "lucide-react";
import type {
  MarketSummaryData,
  IndexData,
  IssueItem,
  HeadlineArticle,
} from "../data/marketSummary";
import type { Article } from "../data/newsSources";
import { runDataVerification } from "../utils/aiSummary";

function formatDisplayDate(dateStr: string): string {
  const match = dateStr.match(/^(\d{4})[-.]\s*(\d{1,2})[-.]\s*(\d{1,2})\s*(?:\(?([일월화수목금토])[요일]*\)?)?/);
  if (match) {
    const [, y, m, d, w] = match;
    const weekShort = w ?? ["일", "월", "화", "수", "목", "금", "토"][new Date(parseInt(y!), parseInt(m!) - 1, parseInt(d!)).getDay()];
    return `${y}. ${m.padStart(2, "0")}. ${d.padStart(2, "0")} (${weekShort})`;
  }
  return dateStr;
}

function BlockTitle({ emoji, children }: { emoji?: string; children: React.ReactNode }) {
  return (
    <div className="mt-[22px] pt-[22px] pb-0 first:mt-0 first:pt-[22px] first:pb-0 border-t border-dashed border-white/10 first:border-t-0">
      <span style={{ fontSize: 16, fontWeight: 700, lineHeight: 1.5 }} className="text-white">
        {emoji && <span className="mr-2">{emoji}</span>}
        {children}
      </span>
    </div>
  );
}

function UsedArticlesSection({ articles }: { articles?: Article[] }) {
  if (!Array.isArray(articles) || articles.length === 0) return null;
  const list = articles.filter((a) => a && typeof a.title === "string");
  if (list.length === 0) return null;

  const bySource = new Map<string, Article[]>();
  for (const a of list) {
    const src = a.source || "(출처 없음)";
    if (!bySource.has(src)) bySource.set(src, []);
    bySource.get(src)!.push(a);
  }

  return (
    <div
      style={{ fontSize: 11 }}
      className="text-gray-400 mt-4 pt-4 pb-6 border-t border-dashed border-white/8"
    >
      <div style={{ fontWeight: 600 }} className="text-gray-400 mb-3">
        사용된 기사 ({list.length})
      </div>
      <div className="space-y-4">
        {Array.from(bySource.entries()).map(([source, items]) => (
          <div key={source}>
            <div style={{ fontWeight: 600 }} className="text-gray-400 mb-1.5">
              {source}
            </div>
            <div className="space-y-1">
              {items.map((a, i) => (
                <a
                  key={a.id || i}
                  href={a.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="block text-gray-400 hover:text-white/80 hover:underline transition-colors"
                  title={a.title}
                >
                  {a.title}
                </a>
              ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

export function MarketSummaryView({
  data: initialData,
  aiModel,
  articles,
}: {
  data: MarketSummaryData;
  aiModel: "gemini" | "gpt";
  articles?: Article[];
}) {
  const [data, setData] = useState<MarketSummaryData>(initialData);
  const isInternational = data.regionLabel.includes("해외") || data.regionLabel.includes("글로벌");
  const containerRef = useRef<HTMLDivElement>(null);
  const [verifyState, setVerifyState] = useState<"idle" | "loading" | "done" | "error">("idle");
  const [verifyMsg, setVerifyMsg] = useState<string | null>(null);

  useEffect(() => { setData(initialData); setVerifyState("idle"); setVerifyMsg(null); }, [initialData]);

  const handleVerify = async () => {
    setVerifyState("loading");
    setVerifyMsg(null);
    try {
      const result = await runDataVerification(data);
      setData(result.correctedData);
      const pct = result.matchPercent;
      setVerifyMsg(pct < 100
        ? `⚠️ 실제 시장 데이터와 상충하는 ${result.correctedCount}개의 항목이 자동 교정되었습니다.`
        : null);
      setVerifyState("done");
    } catch {
      setVerifyState("error");
      setVerifyMsg("검증 중 오류가 발생했습니다.");
    }
  };

  const verifyBadge = data.verificationResult?.isVerified
    ? `데이터 검증 완료 (실제 데이터 일치율: ${data.verificationResult.matchPercent}%)`
    : null;

  const header = (
    <div className="flex items-center justify-between px-[17px] pt-[26px] pb-[26px] border-b border-dashed border-white/10">
      <div>
        <div style={{ fontSize: 11, lineHeight: 1.5 }} className="text-white/90">
          {formatDisplayDate(data.date)}
        </div>
        <div style={{ fontSize: 18, fontWeight: 700, lineHeight: 1.5 }}>
          {isInternational ? "해외 시황 요약" : "한국 시장 뉴스"}
        </div>
        <div style={{ fontSize: 11, lineHeight: 1.5 }} className="text-white/40 mt-[6px]">
          Generated by {aiModel === "gemini" ? "Gemini AI" : "ChatGPT"}
        </div>
      </div>
      <div className="flex items-center gap-2">
        <button
          type="button"
          onClick={handleVerify}
          disabled={verifyState === "loading"}
          className={`flex items-center gap-1.5 px-3 py-1.5 rounded-[6px] border transition-colors text-sm font-medium ${
            verifyState === "done"
              ? "border-emerald-500/40 bg-emerald-500/10 text-emerald-400"
              : verifyState === "loading"
                ? "border-white/10 bg-white/5 text-white/40 cursor-not-allowed"
                : "border-white/10 bg-white/5 text-white/60 hover:text-white/80 hover:bg-white/10"
          }`}
          style={{ fontSize: 12 }}
          title="데이터 검증"
        >
          <ShieldCheck size={14} />
          {verifyState === "loading" ? "검증 중..." : verifyState === "done" ? "검증 완료" : "데이터 검증"}
        </button>
      </div>
    </div>
  );

  const lineStyle = { lineHeight: 1.5 as const };
  const totalAssessmentLabel = isInternational ? "📝 오늘의 시황 총평" : "📝 총평";

  if (isInternational) {
    return (
      <div ref={containerRef} className="bg-white/5 border border-white/8 rounded-[10px] overflow-hidden">
        {header}
        <div className="px-5 py-0 pb-6">

          {/* 검증 완료 배지 */}
          {verifyBadge && (
            <div className="mt-[18px] px-4 py-2.5 rounded-[8px] bg-emerald-500/10 border border-emerald-500/25">
              <span style={{ fontSize: 13, lineHeight: 1.5 }} className="text-emerald-400">✅ {verifyBadge}</span>
            </div>
          )}

          {/* 총평 */}
          <div className="mt-[22px] pt-[22px] pb-0 first:mt-0 first:pt-[22px] first:pb-0 border-t border-dashed border-white/10 first:border-t-0">
            <span style={{ fontSize: 16, fontWeight: 700, lineHeight: 1.5 }} className="text-white">{totalAssessmentLabel}</span>
            <div style={{ fontSize: 14, lineHeight: 1.6 }} className="text-white/80 mt-[14px] min-h-[20px]">
              {data.totalAssessment ? data.totalAssessment : data.totalAssessmentError ? "Error" : ""}
            </div>
          </div>

          {/* 대표 지수 */}
          <BlockTitle emoji="📊">대표 지수</BlockTitle>
          <div className="flex flex-col gap-y-[4px] mt-[14px]" style={lineStyle}>
            {data.indices.map((idx: IndexData, i: number) => (
              <div key={i} className="flex items-baseline gap-2">
                <span style={{ fontSize: 14 }} className="text-white">{idx.name}</span>
                <span style={{ fontSize: 14 }} className={idx.isUp ? "text-emerald-400" : "text-red-400"}>
                  {idx.value} {idx.change}
                </span>
                {idx.changeAbs && (
                  <span style={{ fontSize: 14 }} className={idx.isUp ? "text-emerald-400/80" : "text-red-400/80"}>
                    {idx.changeAbs}
                  </span>
                )}
              </div>
            ))}
          </div>
          {data.indicesSources.length > 0 && (
            <div style={{ fontSize: 13, ...lineStyle }} className="text-white/40 mt-[16px] mb-[22px]">
              출처: {data.indicesSources.map((s) => s.outlet).join(", ")}
            </div>
          )}

          {/* 실시간 주요 언론사별 기사 (RSS 원문 직결) */}
          <BlockTitle emoji="📰">실시간 주요 언론사별 기사</BlockTitle>
          {data.headlineArticles && data.headlineArticles.length > 0 ? (
            <div className="mt-[14px] space-y-[18px]">
              {data.headlineArticles.map((item: HeadlineArticle, i: number) => (
                <div key={i} className="border-l-2 border-[#618EFF]/30 pl-3">
                  <div className="flex items-center gap-2 mb-[5px]">
                    <span style={{ fontSize: 11, fontWeight: 700, letterSpacing: "0.05em" }} className="text-[#618EFF]/90">
                      {item.sourceName}
                    </span>
                    <span style={{ fontSize: 10 }} className="text-white/20">RSS</span>
                  </div>
                  {item.url ? (
                    <a
                      href={item.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      style={{ fontSize: 14, fontWeight: 500, ...lineStyle }}
                      className="text-white/95 hover:text-white hover:underline transition-colors block"
                    >
                      {item.title}
                    </a>
                  ) : (
                    <div style={{ fontSize: 14, fontWeight: 500, ...lineStyle }} className="text-white/95">
                      {item.title}
                    </div>
                  )}
                  {item.summary && item.summary !== "(본문 미수집)" && (
                    <div style={{ fontSize: 13, ...lineStyle }} className="text-white/50 mt-[6px]">
                      {item.summary}
                    </div>
                  )}
                </div>
              ))}
            </div>
          ) : data.noHeadlineArticlesMessage ? (
            <div className="mt-[14px] px-4 py-3 rounded-[8px] bg-white/5 border border-white/8">
              {data.noHeadlineArticlesMessage.split("\n").map((line, i) => (
                <div key={i} style={{ fontSize: i === 0 ? 14 : 12, ...lineStyle }} className={i === 0 ? "text-white/50" : "text-white/30 mt-1"}>
                  {line}
                </div>
              ))}
            </div>
          ) : (
            <div className="mt-[14px] space-y-3">
              {data.keyIssues.slice(0, 10).map((item: IssueItem, i: number) => (
                <div key={i}>
                  <div style={{ fontSize: 14, fontWeight: 500, ...lineStyle }} className="text-white/95">
                    {item.title}
                  </div>
                  <div style={{ fontSize: 14, ...lineStyle }} className="text-white/60 mt-2">
                    {item.body}
                  </div>
                </div>
              ))}
            </div>
          )}
          {data.keyIssuesSources.length > 0 && (
            <div style={{ fontSize: 13, ...lineStyle }} className="text-white/40 mt-[16px] mb-[22px]">
              출처: {data.keyIssuesSources.map((s) => s.outlet).join(", ")}
            </div>
          )}

          {/* M7·반도체주 등락 */}
          {(data.moversUp.length > 0 || data.moversDown.length > 0) && (
            <>
              <BlockTitle emoji="📈">{data.stockMoversLabel}</BlockTitle>
              <div className="mt-[14px] space-y-[9px]">
                {data.moversUp.map((m, i) => (
                  <div key={i}>
                    <div className="flex items-baseline gap-2 flex-wrap">
                      <span style={{ fontSize: 14, fontWeight: 500, ...lineStyle }} className="text-white/90">{m.name}</span>
                      <span style={{ fontSize: 14 }} className="text-white/40">({m.ticker})</span>
                      <span style={{ fontSize: 14 }} className={m.isUp ? "text-emerald-400" : "text-red-400"}>{m.changeRate}</span>
                    </div>
                    <div style={{ fontSize: 14, ...lineStyle }} className="text-white/55 mt-[2px]">{m.reason}</div>
                  </div>
                ))}
                {data.moversDown.map((m, i) => (
                  <div key={i} className={i === 0 ? "mt-[18px]" : ""}>
                    <div className="flex items-baseline gap-2 flex-wrap">
                      <span style={{ fontSize: 14, fontWeight: 500, ...lineStyle }} className="text-white/90">{m.name}</span>
                      <span style={{ fontSize: 14 }} className="text-white/40">({m.ticker})</span>
                      <span style={{ fontSize: 14 }} className={m.isUp ? "text-emerald-400" : "text-red-400"}>{m.changeRate}</span>
                    </div>
                    <div style={{ fontSize: 14, ...lineStyle }} className="text-white/55 mt-[2px]">{m.reason}</div>
                  </div>
                ))}
              </div>
              {data.moversSources.length > 0 && (
                <div style={{ fontSize: 13, ...lineStyle }} className="text-white/40 mt-[16px] mb-[22px]">
                  출처: {data.moversSources.map((s) => s.outlet).join(", ")}
                </div>
              )}
            </>
          )}

          {/* 국제 정세 기사 */}
          {data.geopoliticalLabel && data.geopoliticalIssues && data.geopoliticalIssues.length > 0 && (
            <>
              <BlockTitle emoji="🌍">국제 정세 기사</BlockTitle>
              <div className="mt-[14px] space-y-[9px]">
                {data.geopoliticalIssues.slice(0, 7).map((item: IssueItem, i: number) => (
                  <div key={i}>
                    <div style={{ fontSize: 14, fontWeight: 500, ...lineStyle }} className="text-white/90">{item.title}</div>
                    <div style={{ fontSize: 14, ...lineStyle }} className="text-white/58 mt-[2px]">{item.body}</div>
                  </div>
                ))}
              </div>
              {data.geopoliticalSources && data.geopoliticalSources.length > 0 && (
                <div style={{ fontSize: 13, ...lineStyle }} className="text-white/40 mt-[16px] mb-[22px]">
                  출처: {data.geopoliticalSources.map((s) => s.outlet).join(", ")}
                </div>
              )}
            </>
          )}

          {/* 검증 결과 + 교정 전후 상세 */}
          {verifyState === "done" && data.verificationResult && (
            <>
              {verifyMsg && (
                <div className="mt-4 px-4 py-2.5 rounded-[8px] bg-amber-500/10 border border-amber-500/25">
                  <span style={{ fontSize: 13, lineHeight: 1.5 }} className="text-amber-400">{verifyMsg}</span>
                </div>
              )}
              {data.verificationResult.corrections && data.verificationResult.corrections.length > 0 && (
                <div className="mt-3 space-y-2">
                  <div style={{ fontSize: 12, fontWeight: 600 }} className="text-white/40 mb-1">⚠️ 수치 불일치 항목 발견</div>
                  {data.verificationResult.corrections.map((c, i) => (
                    <div key={i} className="px-3 py-2 rounded-[6px] bg-white/3 border border-white/6">
                      <div style={{ fontSize: 11, fontWeight: 600 }} className="text-white/40 mb-[4px]">{c.field}</div>
                      {c.original && (
                        <div style={{ fontSize: 12, lineHeight: 1.5 }} className="text-red-400/80">수정 전: {c.original}</div>
                      )}
                      <div style={{ fontSize: 12, lineHeight: 1.5 }} className="text-emerald-400/80">기준값: {c.corrected}</div>
                    </div>
                  ))}
                </div>
              )}
            </>
          )}
          {verifyState === "error" && verifyMsg && (
            <div className="mt-4 px-4 py-2.5 rounded-[8px] bg-red-500/10 border border-red-500/25">
              <span style={{ fontSize: 13, lineHeight: 1.5 }} className="text-red-400">{verifyMsg}</span>
            </div>
          )}
          {/* 해외 뷰: 헤드라인 섹션이 RSS 기사를 이미 표시하므로 "사용된 기사" 섹션 제거 */}
        </div>
      </div>
    );
  }

  // 국내 뉴스
  return (
    <div ref={containerRef} className="bg-white/5 border border-white/8 rounded-[10px] overflow-hidden">
      {header}
      <div className="px-5 py-0 pb-6">
        {verifyBadge && (
          <div className="mt-[18px] px-4 py-2.5 rounded-[8px] bg-emerald-500/10 border border-emerald-500/25">
            <span style={{ fontSize: 13, lineHeight: 1.5 }} className="text-emerald-400">✅ {verifyBadge}</span>
          </div>
        )}
        <div className="mt-[22px] pt-[22px] pb-0 first:mt-0 first:pt-[22px] first:pb-0 border-t border-dashed border-white/10 first:border-t-0">
          <span style={{ fontSize: 16, fontWeight: 700, lineHeight: 1.5 }} className="text-white">{totalAssessmentLabel}</span>
          <div style={{ fontSize: 14, lineHeight: 1.6 }} className="text-white/80 mt-[14px] min-h-[20px]">
            {data.totalAssessment ? data.totalAssessment : data.totalAssessmentError ? "Error" : ""}
          </div>
        </div>
        <BlockTitle emoji="📊">대표 지수</BlockTitle>
        <div className="flex flex-col gap-y-[4px] mt-[14px]" style={lineStyle}>
          {data.indices.map((idx: IndexData, i: number) => (
            <div key={i} className="flex items-baseline gap-2">
              <span style={{ fontSize: 14 }} className="text-white">{idx.name}</span>
              <span style={{ fontSize: 14 }} className={idx.isUp ? "text-emerald-400" : "text-red-400"}>
                {idx.value} {idx.change}
              </span>
              {idx.changeAbs && (
                <span style={{ fontSize: 14 }} className={idx.isUp ? "text-emerald-400/80" : "text-red-400/80"}>
                  {idx.changeAbs}
                </span>
              )}
            </div>
          ))}
        </div>
        {data.indicesSources.length > 0 && (
          <div style={{ fontSize: 13, ...lineStyle }} className="text-white/40 mt-[16px] mb-[22px]">
            출처: {data.indicesSources.map((s) => s.outlet).join(", ")}
          </div>
        )}

        <BlockTitle emoji="📋">주요 헤드라인 기사</BlockTitle>
        <div className="mt-[14px] space-y-3">
          {data.keyIssues.slice(0, 12).map((item: IssueItem, i: number) => (
            <div key={i}>
              <div style={{ fontSize: 14, fontWeight: 500, ...lineStyle }} className="text-white/95">
                {item.title}
              </div>
              <div style={{ fontSize: 14, ...lineStyle }} className="text-white/60 mt-2">
                {item.body}
              </div>
            </div>
          ))}
        </div>
        {data.keyIssuesSources.length > 0 && (
          <div style={{ fontSize: 13, ...lineStyle }} className="text-white/40 mt-[16px] mb-[22px]">
            출처: {data.keyIssuesSources.map((s) => s.outlet).join(", ")}
          </div>
        )}

        {/* 실적발표 이슈 - hidden */}

        {verifyState === "done" && data.verificationResult && (
          <>
            {verifyMsg && (
              <div className="mt-4 px-4 py-2.5 rounded-[8px] bg-amber-500/10 border border-amber-500/25">
                <span style={{ fontSize: 13, lineHeight: 1.5 }} className="text-amber-400">{verifyMsg}</span>
              </div>
            )}
            {data.verificationResult.corrections && data.verificationResult.corrections.length > 0 && (
              <div className="mt-3 space-y-2">
                {data.verificationResult.corrections.map((c, i) => (
                  <div key={i} className="px-3 py-2 rounded-[6px] bg-white/3 border border-white/6">
                    <div style={{ fontSize: 11, fontWeight: 600 }} className="text-white/40 mb-[4px]">{c.field}</div>
                    {c.original && <div style={{ fontSize: 12, lineHeight: 1.5 }} className="text-red-400/80">수정 전: {c.original}</div>}
                    <div style={{ fontSize: 12, lineHeight: 1.5 }} className="text-emerald-400/80">기준값: {c.corrected}</div>
                  </div>
                ))}
              </div>
            )}
          </>
        )}
        {verifyState === "error" && verifyMsg && (
          <div className="mt-4 px-4 py-2.5 rounded-[8px] bg-red-500/10 border border-red-500/25">
            <span style={{ fontSize: 13, lineHeight: 1.5 }} className="text-red-400">{verifyMsg}</span>
          </div>
        )}
        <UsedArticlesSection articles={articles} />
      </div>
    </div>
  );
}
