import React, { useRef, useState, useEffect } from "react";
import { Maximize2, Minimize2 } from "lucide-react";
import type {
  MarketSummaryData,
  IndexData,
  IssueItem,
  EarningsItem,
} from "../data/marketSummary";

function formatDisplayDate(dateStr: string): string {
  const match = dateStr.match(/^(\d{4})[-.]\s*(\d{1,2})[-.]\s*(\d{1,2})\s*(?:\(?([일월화수목금토])[요일]*\)?)?/);
  if (match) {
    const [, y, m, d, w] = match;
    const weekShort = w ?? ["일", "월", "화", "수", "목", "금", "토"][new Date(parseInt(y!), parseInt(m!) - 1, parseInt(d!)).getDay()];
    return `${y}. ${m.padStart(2, "0")}. ${d.padStart(2, "0")} (${weekShort})`;
  }
  return dateStr;
}

function BlockTitle({ emoji, children }: { emoji?: string; children: React.ReactNode }) {
  return (
    <div className="mt-[22px] pt-[22px] pb-0 first:mt-0 first:pt-[22px] first:pb-0 border-t border-dashed border-white/10 first:border-t-0">
      <span style={{ fontSize: 16, fontWeight: 700, lineHeight: 1.5 }} className="text-white">
        {emoji && <span className="mr-2">{emoji}</span>}
        {children}
      </span>
    </div>
  );
}

export function MarketSummaryView({
  data,
  aiModel,
}: {
  data: MarketSummaryData;
  aiModel: "gemini" | "gpt";
}) {
  const isInternational = data.regionLabel.includes("해외");
  const containerRef = useRef<HTMLDivElement>(null);
  const [isFullscreen, setIsFullscreen] = useState(false);

  useEffect(() => {
    const handler = () => {
      setIsFullscreen(!!document.fullscreenElement);
    };
    document.addEventListener("fullscreenchange", handler);
    document.addEventListener("webkitfullscreenchange", handler);
    return () => {
      document.removeEventListener("fullscreenchange", handler);
      document.removeEventListener("webkitfullscreenchange", handler);
    };
  }, []);

  const handleToggleFullscreen = () => {
    if (!containerRef.current) return;
    if (isFullscreen) {
      const exitFs = document.exitFullscreen ?? (document as { webkitExitFullscreen?: () => Promise<void> }).webkitExitFullscreen;
      if (exitFs) exitFs.call(document);
    } else {
      const el = containerRef.current;
      const reqFs = el.requestFullscreen ?? (el as { webkitRequestFullscreen?: () => Promise<void> }).webkitRequestFullscreen;
      if (reqFs) reqFs.call(el);
    }
  };

  const header = (
    <div className="flex items-center justify-between px-[17px] pt-[26px] pb-[26px] border-b border-dashed border-white/10">
      <div>
        <div style={{ fontSize: 11, lineHeight: 1.5 }} className="text-white/90">
          {formatDisplayDate(data.date)}
        </div>
        <div style={{ fontSize: 18, fontWeight: 700, lineHeight: 1.5 }}>{data.regionLabel}</div>
        <div style={{ fontSize: 11, lineHeight: 1.5 }} className="text-white/40 mt-[6px]">
          Generated by {aiModel === "gemini" ? "Gemini AI" : "ChatGPT"}
        </div>
      </div>
      <div className="flex items-center gap-2">
        <button
          type="button"
          onClick={handleToggleFullscreen}
          className="p-1.5 rounded-[6px] text-white/50 hover:text-white/80 hover:bg-white/5 transition-colors"
          title={isFullscreen ? "전체 화면 닫기" : "전체 화면"}
          aria-label={isFullscreen ? "전체 화면 닫기" : "전체 화면"}
        >
          {isFullscreen ? <Minimize2 size={16} /> : <Maximize2 size={16} />}
        </button>
      </div>
    </div>
  );

  const lineStyle = { lineHeight: 1.5 as const };

  if (isInternational) {
    return (
      <div ref={containerRef} className={`bg-white/5 border border-white/8 rounded-[10px] overflow-hidden ${isFullscreen ? "!bg-[#0a0a0f] overflow-y-auto min-h-full pt-[52px]" : ""}`}>
        {header}
        <div className="px-5 py-0 pb-6">
          <div className="mt-[22px] pt-[22px] pb-0 first:mt-0 first:pt-[22px] first:pb-0 border-t border-dashed border-white/10 first:border-t-0">
            <span style={{ fontSize: 16, fontWeight: 700, lineHeight: 1.5 }} className="text-white">📝 오늘의 시황 총평</span>
            <div style={{ fontSize: 14, lineHeight: 1.6 }} className="text-white/80 mt-[14px] min-h-[20px]">
              {data.totalAssessment ? data.totalAssessment : data.totalAssessmentError ? "Error" : ""}
            </div>
          </div>
          <BlockTitle emoji="📊">대표 지수</BlockTitle>
          <div className="flex flex-col gap-y-[4px] mt-[14px]" style={lineStyle}>
            {data.indices.map((idx: IndexData, i: number) => (
              <div key={i} className="flex items-baseline gap-2">
                <span style={{ fontSize: 14 }} className="text-white">{idx.name}</span>
                <span style={{ fontSize: 14 }} className={idx.isUp ? "text-emerald-400" : "text-red-400"}>
                  {idx.value} {idx.change}
                </span>
                {idx.changeAbs && (
                  <span style={{ fontSize: 14 }} className={idx.isUp ? "text-emerald-400/80" : "text-red-400/80"}>
                    {idx.changeAbs}
                  </span>
                )}
              </div>
            ))}
          </div>
          {data.indicesSources.length > 0 && (
            <div style={{ fontSize: 13, ...lineStyle }} className="text-white/40 mt-[16px] mb-[22px]">
              출처: {data.indicesSources.map((s) => s.outlet).join(", ")}
            </div>
          )}

          <BlockTitle emoji="📋">주요 이슈 정리</BlockTitle>
          <div className="mt-[14px] space-y-3">
            {data.keyIssues.slice(0, isInternational ? 10 : 12).map((item: IssueItem, i: number) => (
              <div key={i}>
                <div style={{ fontSize: 14, fontWeight: 500, ...lineStyle }} className="text-white/95">
                  {item.title}
                </div>
                <div style={{ fontSize: 14, ...lineStyle }} className="text-white/60 mt-2">
                  {item.body}
                </div>
              </div>
            ))}
          </div>
          {data.keyIssuesSources.length > 0 && (
            <div style={{ fontSize: 13, ...lineStyle }} className="text-white/40 mt-[16px] mb-[22px]">
              출처: {data.keyIssuesSources.map((s) => s.outlet).join(", ")}
            </div>
          )}

          <BlockTitle emoji="📈">{data.stockMoversLabel}</BlockTitle>
          <div className="mt-[14px] space-y-[9px]">
            <div style={{ fontSize: 14, fontWeight: 600, ...lineStyle }} className="text-white">상승</div>
            {data.moversUp.map((m, i) => (
              <div key={i}>
                <div className="flex items-baseline gap-2 flex-wrap">
                  <span style={{ fontSize: 14, fontWeight: 500, ...lineStyle }} className="text-white/90">{m.name}</span>
                  <span style={{ fontSize: 14 }} className="text-white/40">({m.ticker})</span>
                  <span style={{ fontSize: 14 }} className={m.isUp ? "text-emerald-400" : "text-red-400"}>{m.changeRate}</span>
                </div>
                <div style={{ fontSize: 14, ...lineStyle }} className="text-white/55 mt-[2px]">{m.reason}</div>
              </div>
            ))}
            <div style={{ fontSize: 14, fontWeight: 600, ...lineStyle }} className="text-white mt-[18px]">하락</div>
            {data.moversDown.map((m, i) => (
              <div key={i}>
                <div className="flex items-baseline gap-2 flex-wrap">
                  <span style={{ fontSize: 14, fontWeight: 500, ...lineStyle }} className="text-white/90">{m.name}</span>
                  <span style={{ fontSize: 14 }} className="text-white/40">({m.ticker})</span>
                  <span style={{ fontSize: 14 }} className={m.isUp ? "text-emerald-400" : "text-red-400"}>{m.changeRate}</span>
                </div>
                <div style={{ fontSize: 14, ...lineStyle }} className="text-white/55 mt-[2px]">{m.reason}</div>
              </div>
            ))}
          </div>
          {data.moversSources.length > 0 && (
            <div style={{ fontSize: 13, ...lineStyle }} className="text-white/40 mt-[16px] mb-[22px]">
              출처: {data.moversSources.map((s) => s.outlet).join(", ")}
            </div>
          )}

          {data.geopoliticalLabel && data.geopoliticalIssues && data.geopoliticalIssues.length > 0 && (
            <>
              <BlockTitle emoji="🌍">{data.geopoliticalLabel}</BlockTitle>
              <div className="mt-[14px] space-y-[9px]">
                {data.geopoliticalIssues.slice(0, 7).map((item: IssueItem, i: number) => (
                  <div key={i}>
                    <div style={{ fontSize: 14, fontWeight: 500, ...lineStyle }} className="text-white/90">{item.title}</div>
                    <div style={{ fontSize: 14, ...lineStyle }} className="text-white/58 mt-[2px]">{item.body}</div>
                  </div>
                ))}
              </div>
              {data.geopoliticalSources && data.geopoliticalSources.length > 0 && (
                <div style={{ fontSize: 13, ...lineStyle }} className="text-white/40 mt-[16px] mb-[22px]">
                  출처: {data.geopoliticalSources.map((s) => s.outlet).join(", ")}
                </div>
              )}
            </>
          )}

          {/* 해외 시황: 실적발표 영역 항상 표시 */}
          <>
            <BlockTitle emoji="💰">실적발표 이슈</BlockTitle>
            <div className="mt-[14px]">
              {data.earningsPast && data.earningsPast.length > 0 ? (
                <>
                  <div style={{ fontSize: 14, fontWeight: 600, ...lineStyle }} className="text-white">간밤 실적 결과</div>
                  <div className="space-y-[9px] mt-[9px]">
                    {data.earningsPast.map((e: EarningsItem, i: number) => (
                      <div key={i}>
                        <div className="flex items-baseline gap-2 flex-wrap">
                          <span style={{ fontSize: 14, fontWeight: 500, ...lineStyle }} className="text-white/90">{e.company}</span>
                          <span style={{ fontSize: 14 }} className="text-white/40">({e.ticker})</span>
                          {e.changeRate && (
                            <span style={{ fontSize: 14 }} className={e.changeRate.startsWith("+") ? "text-emerald-400" : "text-red-400"}>
                              {e.changeRate}
                            </span>
                          )}
                        </div>
                        <div style={{ fontSize: 14, ...lineStyle }} className="text-white/55 mt-[2px]">{e.result}</div>
                      </div>
                    ))}
                  </div>
                </>
              ) : (
                <div style={{ fontSize: 14 }} className="text-white/50">뉴스에서 실적 발표 결과를 찾지 못했습니다.</div>
              )}
              {data.earningsUpcoming && data.earningsUpcoming.length > 0 ? (
                <>
                  <div style={{ fontSize: 14, fontWeight: 600, ...lineStyle }} className="text-white mt-[18px]">예정 발표 일정</div>
                  <div className="space-y-[4px] mt-[9px]" style={lineStyle}>
                    {data.earningsUpcoming.map((s, i) => (
                      <div key={i} style={{ fontSize: 14 }} className="text-white/55">• {s}</div>
                    ))}
                  </div>
                </>
              ) : (
                <div style={{ fontSize: 14 }} className="text-white/50 mt-[12px]">예정된 실적발표가 없습니다.</div>
              )}
            </div>
            {data.earningsSources && data.earningsSources.length > 0 && (
              <div style={{ fontSize: 13, ...lineStyle }} className="text-white/40 mt-[16px] mb-[22px]">
                출처: {data.earningsSources.map((s) => s.outlet).join(", ")}
              </div>
            )}
          </>
        </div>
      </div>
    );
  }

  return (
    <div ref={containerRef} className={`bg-white/5 border border-white/8 rounded-[10px] overflow-hidden ${isFullscreen ? "!bg-[#0a0a0f] overflow-y-auto min-h-full pt-[52px]" : ""}`}>
      {header}
      <div className="px-5 py-0">
        <div className="mt-[22px] pt-[22px] pb-0 first:mt-0 first:pt-[22px] first:pb-0 border-t border-dashed border-white/10 first:border-t-0">
          <span style={{ fontSize: 16, fontWeight: 700, lineHeight: 1.5 }} className="text-white">📝 오늘의 시황 총평</span>
          <div style={{ fontSize: 14, lineHeight: 1.6 }} className="text-white/80 mt-[14px] min-h-[20px]">
            {data.totalAssessment ? data.totalAssessment : data.totalAssessmentError ? "Error" : ""}
          </div>
        </div>
        <BlockTitle emoji="📊">대표 지수</BlockTitle>
        <div className="flex flex-col gap-y-[4px] mt-[14px]" style={lineStyle}>
          {data.indices.map((idx: IndexData, i: number) => (
            <div key={i} className="flex items-baseline gap-2">
              <span style={{ fontSize: 14 }} className="text-white">{idx.name}</span>
              <span style={{ fontSize: 14 }} className={idx.isUp ? "text-emerald-400" : "text-red-400"}>
                {idx.value} {idx.change}
              </span>
              {idx.changeAbs && (
                <span style={{ fontSize: 14 }} className={idx.isUp ? "text-emerald-400/80" : "text-red-400/80"}>
                  {idx.changeAbs}
                </span>
              )}
            </div>
          ))}
        </div>
        {data.indicesSources.length > 0 && (
          <div style={{ fontSize: 13, ...lineStyle }} className="text-white/40 mt-[16px] mb-[22px]">
            출처: {data.indicesSources.map((s) => s.outlet).join(", ")}
          </div>
        )}

        <BlockTitle emoji="📋">주요 이슈 정리</BlockTitle>
        <div className="mt-[14px] space-y-3">
          {data.keyIssues.slice(0, isInternational ? 10 : 12).map((item: IssueItem, i: number) => (
            <div key={i}>
              <div style={{ fontSize: 14, fontWeight: 500, ...lineStyle }} className="text-white/95">
                {item.title}
              </div>
              <div style={{ fontSize: 14, ...lineStyle }} className="text-white/60 mt-2">
                {item.body}
              </div>
            </div>
          ))}
        </div>
        {data.keyIssuesSources.length > 0 && (
          <div style={{ fontSize: 13, ...lineStyle }} className="text-white/40 mt-[16px] mb-[22px]">
            출처: {data.keyIssuesSources.map((s) => s.outlet).join(", ")}
          </div>
        )}

        {data.geopoliticalLabel && data.geopoliticalIssues && data.geopoliticalIssues.length > 0 && (
          <>
            <BlockTitle emoji="🌍">{data.geopoliticalLabel}</BlockTitle>
            <div className="mt-[14px] space-y-[9px]">
              {data.geopoliticalIssues.slice(0, 7).map((item: IssueItem, i: number) => (
                <div key={i}>
                  <div style={{ fontSize: 14, fontWeight: 500, ...lineStyle }} className="text-white/90">{item.title}</div>
                  <div style={{ fontSize: 14, ...lineStyle }} className="text-white/58 mt-[2px]">{item.body}</div>
                </div>
              ))}
            </div>
            {data.geopoliticalSources && data.geopoliticalSources.length > 0 && (
              <div style={{ fontSize: 13, ...lineStyle }} className="text-white/40 mt-[16px] mb-[22px]">
                출처: {data.geopoliticalSources.map((s) => s.outlet).join(", ")}
              </div>
            )}
          </>
        )}

        {data.earningsPast && data.earningsPast.length > 0 && (
          <>
            <BlockTitle emoji="💰">실적발표 이슈</BlockTitle>
            <div className="mt-[14px]">
              <div style={{ fontSize: 14, fontWeight: 600, ...lineStyle }} className="text-white">간밤 실적 결과</div>
              <div className="space-y-[9px] mt-[9px]">
                {data.earningsPast.map((e: EarningsItem, i: number) => (
                  <div key={i}>
                    <div className="flex items-baseline gap-2 flex-wrap">
                      <span style={{ fontSize: 14, fontWeight: 500, ...lineStyle }} className="text-white/90">{e.company}</span>
                      <span style={{ fontSize: 14 }} className="text-white/40">({e.ticker})</span>
                      {e.changeRate && (
                        <span style={{ fontSize: 14 }} className={e.changeRate.startsWith("+") ? "text-emerald-400" : "text-red-400"}>
                          {e.changeRate}
                        </span>
                      )}
                    </div>
                    <div style={{ fontSize: 14, ...lineStyle }} className="text-white/55 mt-[2px]">{e.result}</div>
                  </div>
                ))}
              </div>
            </div>
            {data.earningsUpcoming && data.earningsUpcoming.length > 0 && (
              <>
                <div style={{ fontSize: 14, fontWeight: 600, ...lineStyle }} className="text-white mt-[18px]">예정 발표 일정</div>
                <div className="space-y-[4px] mt-[9px]" style={lineStyle}>
                  {data.earningsUpcoming.map((s, i) => (
                    <div key={i} style={{ fontSize: 14 }} className="text-white/55">• {s}</div>
                  ))}
                </div>
              </>
            )}
            {data.earningsSources && data.earningsSources.length > 0 && (
              <div style={{ fontSize: 13, ...lineStyle }} className="text-white/40 mt-[16px] mb-[22px]">
                출처: {data.earningsSources.map((s) => s.outlet).join(", ")}
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
}
